logging:
  receivers:
    my-app-receiver:
      type: files
      include_paths:
        - /var/log/webapp/webapp.log
      record_log_file_path: true
  processors:
    my-app-processor:
      type: parse_json
      time_key: time
      time_format: "YYYY-MM-DDTHH:mm:ss.SSSZ"
    severity-processor:
      type: modify_fields
      fields:
        severity: 
          move_from: jsonPayload.level
  service:
    pipelines:
      default_pipeline:
        receivers: [my-app-receiver]
        processors:
            - my-app-processor
            - severity-processor
