name: assignment2workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: admin@12345  # Change this to your desired root password
          MYSQL_DATABASE: webappdb  # Change this to your desired database name
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run compile check
      run: npm start   # Adjust this command according to your project setup

    # - name: Run tests
    #   run: npm test  # Adjust this command according to your project setup
    - name: Stop Node.js server
      run: npm stop   # Adjust this command according to how you stop your Node.js server

    - name: Stop MySQL server
      run: |
        mysql -u root -p'admin@12345' -e "SHUTDOWN;"
        echo "MySQL server stopped successfully!"

    - name: Complete workflow
      run: echo "Workflow completed successfully!"
