name: assignment2workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run compile check
      run: npm run   # Adjust this command according to your project setup

    # - name: Run tests
    #   run: npm test  # Adjust this command according to your project setup

    - name: Complete workflow
      run: echo "Workflow completed successfully!"
