name: packerbuild

on:
  push:
    branches:
      - main

jobs:
  packerbuild:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    permissions:
          contents: 'read'
          id-token: 'write'   
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run compile check
      run: npm run build

    - name: Create .env File
      run: echo "${{ secrets.ENV_CONTENTS }}" > .env

    - name: Run tests
      run: npm test
    
    - name: Install Packer
      run: |
          wget https://releases.hashicorp.com/packer/1.7.6/packer_1.7.6_linux_amd64.zip
          unzip packer_1.7.6_linux_amd64.zip
          sudo mv packer /usr/local/bin/
          packer version


    - name: Initialize packer
      run: |
          packer init .

    - name: Run packer fmt
      run: |
          set -e
          packer fmt -check .

    - name: Run packer validate
      run: |
          set -e
          packer validate .
    
    - name: Set up Google Cloud SDK
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS_PACKER }}

    - name: Debug GCP_APPLICATION_CREDENTIALS secret
      run: echo "${{ secrets.GCP_CREDENTIALS_PACKER }}"

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Run packer build
      run: packer build .

    - name: Authenticate with GCP
      uses: 'google-github-actions/auth@v2'
      with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_FOR_INSTANCE }}

    - name: Debug GCP_APPLICATION_CREDENTIALS secret
      run: echo "${{ secrets.GCP_CREDENTIALS_FOR_INSTANCE }}"

    - name: Get latest image
      id: get-latest-image
      run: |
        image_list=$(gcloud compute images list --filter="name~'packer-.*'" --format="value(NAME, creationTimestamp)" | sort -k2 -r)
        custom_image=$(echo "$image_list" | head -n1 | awk '{print $1}')

        echo "Latest Image: $custom_image"
        
    - name: Create New Instance Template Version
      run: |
          gcloud compute instance-templates create csye6225-instance-template02 \
           --region=us-east1 \
           --instance-template-region=us-east1 \
           --boot-disk-type=pd-standard \
           --machine-type=e2-medium \
           --image=$custom_image \
           --boot-disk-kms-keyring=keyring-10 \
           --boot-disk-kms-location=us-east1 \
           --boot-disk-kms-key=projects/dev-csye6225-415809/locations/us-east1/keyRings/keyring-10/cryptoKeys/vm-cmek-key-1 \
           --metadata=startup-script="#\!/bin/bash
           ENV_FILE=\"/opt/csye6225/webapp/.env\"
           if [ -e \"\$ENV_FILE\" ]; then
              sed -i '1iLOGPATH=/var/log/webapp/' \"\$ENV_FILE\"
              sed -i 's/^DB_HOST=.*/DB_HOST=10.248.0.2/' \"\$ENV_FILE\"
              sed -i 's/^DB_USERNAME=.*/DB_USERNAME=webapp/' \"\$ENV_FILE\"
              sed -i 's/^DB_PASSWORD=.*/DB_PASSWORD=b%gL)k4_+Ccb+vyY/' \"\$ENV_FILE\"
              sed -i 's/^DB_NAME=.*/DB_NAME=webapp/' \"\$ENV_FILE\"
              echo \"\$ENV_FILE\"
          fi
          sudo chown -R csye6225:csye6225 /opt/csye6225/
          sudo chown -R csye6225:csye6225 /var/log/webapp/
          sudo systemctl restart webapp"
          
    - name: Create managed-instance-group
      run: |
          gcloud compute instance-groups managed create csye6225-managed-instance-group02 \
          --base-instance-name=webapp-instance \
          --template=projects/dev-csye6225-415809/regions/us-east1/instanceTemplates/csye6225-instance-template02 \
          --size=3 \
          --zones=us-east1-b,us-east1-c  
      
    - name: auto-scaling 
      run: |
          gcloud compute instance-groups managed set-autoscaling csye6225-managed-instance-group02 \
          --region=us-east1 \
          --min-num-replicas=1 \
          --max-num-replicas=3 \
          --target-cpu-utilization=0.05 \
          --cool-down-period=90

    - name: rolling-update
      run: |
          gcloud compute instance-groups managed rolling-action start-update csye6225-managed-instance-group02 \
          --version=template=projects/dev-csye6225-415809/regions/us-east1/instanceTemplates/csye6225-instance-template02 \
          --region=us-east1

    - name: wait till Status is reached
      run: |
          gcloud compute instance-groups managed wait-until csye6225-managed-instance-group02 \
          --version-target-reached \
          --region=us-east1
    
    - name: wait for rollout Status
      run: |
          #!/bin/bash
          MIG_NAME="csye6225-managed-instance-group02"
          REGION="us-east1"
        
          while true; do
            STATUS=$(gcloud compute instance-groups managed describe $MIG_NAME \
                --region=$REGION \
                --format="value(status.versionTarget.isReached)")
            
            if [ "$STATUS" == "True" ]; then
                echo "Rollout status: true. All VM instances are using the target version."
                break
            else
                echo "Rollout status: false. Waiting for rollout to complete..."
                sleep 30 # Wait for 30 seconds before checking again
            fi
          done


    - name: Complete workflow
      run: echo "Workflow completed successfully!"
